language: csharp
solution: EFCore.PG.sln
dist: trusty
sudo: false
mono: none
dotnet: 2.1.300-rc1-008673

services:
  - postgresql
addons:
  postgresql: "9.6"

env:
  - Test__Npgsql__DefaultConnection: '"Host=localhost;Database=postgres;Username=postgres;Password="'

before_script:
  - psql -c 'CREATE EXTENSION hstore'
  - dotnet restore -v Minimal
script:
  - dotnet test test/EFCore.PG.Tests/EFCore.PG.Tests.csproj
  - dotnet test test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
  - dotnet test test/EFCore.PG.Design.FunctionalTests/EFCore.PG.Design.FunctionalTests.csproj

cache:
  directories:
    - $HOME/.nuget/packages

